### ISSUE TITLE
fog: discrepancy between full fog tile and fog sprite

### ISSUE THREAD

**Issue by kazzmir** [kazzmir/master-of-magic#163]
![image](https://github.com/user-attachments/assets/8f7a0d63-0106-4486-a340-8d4fb6cb2b87)

It looks as thought the pixels used in the fog images are very slightly brighter than a full fog tile (which is just rendered as a black square R=0,G=0,B=0).

I don't see a fog sprite in the lbx data that could be used as a full tile. Maybe the full tile fog color just needs to be adjusted.

**Comment by msom** [comment]
When dumping the fog tiles as png, they appear as `#080404`.
