### ISSUE TITLE
We've been looking for you

### ISSUE THREAD

**Issue by Blakeley00** [kazzmir/master-of-magic#2]
Hi @kazzmir and @drafkind 

I just stumbled across this accidentally. I run the Mater of Magic facebook group and a MoM fan website that tributes fan projects. Are you guys the same "MoM Clone" project as the one that existed on these archived websites below and also released a MoM 0.6.0 demo with multiplayer many years ago? They went under the name "Illustrious Software".

If so is the source you have here a newer version than that old 0.6.0 demo? Whatever happened to this project? Players get a "soccet -error" when they try multiplayer in the old demo, is that because its trying to connect to server game matching software that doesn't exist? And when you say clone just how much of a clone is it really since the source code to original mom is lost?

http://web.archive.org/web/20130726013248/http://www.illustrious-software.co.uk/showpage.php?page=main
http://web.archive.org/web/20051214105151/http://www.masterofmagic.co.uk/

![MClone01](https://user-images.githubusercontent.com/26017445/75657218-9c56ed80-5cb5-11ea-89ab-dca3e5258c94.jpg)

The old website says "George Quinn, Ewen Lee & Lee Gardiner" as the creators which doesn't match your names, so maybe this is another failed clone project?

**Comment by drafkind** [comment]
Hi we are a separate project from those other ones. Chalk us up as another
failed clone.

**Comment by Blakeley00** [comment]
> Hi we are a separate project from those other ones. Chalk us up as another failed clone.

Sorry to hear that @drafkind . Oh well if you and @kazzmir are still interesting in talking about or watching other rebuild attempts then feel free to come join the [Master of Magic Discord](https://discord.gg/wFNQf36) that I help run. We recently created a MoM Reverse Engineering sub chat there as another fellow is working on a similar project to rewrite MoM and Civizard (the MoM playstation remake).

Implode who made the [Master of Magic HD Multiplayer remake](https://sourceforge.net/projects/momime/) over the last 15 years that's getting very complete now also lurks our discord too as he's still working away on MoM-IME (recently implemented working global AI and taught it to build roads in between trying to kill you lol!).

I found [another group here on github](https://github.com/Jakz/openmom) who appear to be working on a similar project called Open-MoM and I can see there's been work on their files even in the last few months so I might invite them too.

And finally I'm not sure how connected you guys are to the MoM fan community these days and MoM news but as previously mentioned I run a [Facebook MoM group](https://www.facebook.com/groups/MasterOfMagicGame) and help run the Discord too. We try to keep up to date on all official and fan projects so if you've been missing out on all the good MoM news then come drop by! :)

For example Slitherine have purchased the MoM rights from Atari and are selling MoM on GoG & steam, and best of all appear to be working on a official MoM2 sequel!! They're super keen to get their hands on MoM's long lost source code and have expressed interest in rebuild projects too.. They started working with Caster of Magic creator Seravy and are now selling his MoM mod as an official addon! He too is currently rebuilding MoM from the ground up (except he's using his 10-15 years of hacking every part on MoM to rebuild it super quick) and is making a Caster of Magic 2 which he's already posting public alphas over at the [Realms Beyond MoM forum](http://www.realmsbeyond.net/forums/showthread.php?tid=10020). Slitherine have also made a new official Master of Magic forum too. I actually [made a thread there](http://www.slitherine.com/forum/viewtopic.php?f=590&t=97156) telling them about all the source possibilities and rebuild projects I knew and included yours.

I think that's all the good stuff haha.. Hope to see you guys in the communities some time if you're not already there as your knowledge and experience of tinkering with MoM files would be most welcome. :)

**Comment by Blakeley00** [comment]
Just a quick update guys.. Jim's MoM rebuild project on the [Master of Magic Discord]([https://discord.gg/wFNQf36](https://discord.gg/wFNQf36) has gotten quite far now so here's some links if of interest..
Github: https://github.com/jbalcomb/ReMoM/
Video: https://youtu.be/d-PlvxV_Ek0

**Comment by Blakeley00** [comment]
Just a quick update for you guys ( @kazzmir & @drafkind ).. Jim's opensource MoM reassembly project in the [Master of Magic Discord](https://discord.gg/wFNQf36) reverse engineering area has gotten quite far now so here's some links if of interest..
Github: https://github.com/jbalcomb/ReMoM/
Video: https://youtu.be/d-PlvxV_Ek0

**Comment by kazzmir** [comment]
I joined the magic discord server and talk to Jim frequently. Closing this for now.
